import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import { admin,errorResponse,json,HttpError,sameOrigin } from '@/lib/server';
import { rawDatabase } from '@/lib/database';
import { newInvitation } from '@/lib/auth';
import { withBase } from '@/lib/paths';
export async function GET(){try{await admin();const members=rawDatabase().prepare('SELECT email,name,role,primary_admin FROM members WHERE disabled=0 ORDER BY primary_admin DESC,name').all();return json({members})}catch(e){return errorResponse(e)}}
export async function POST(r:Request){try{sameOrigin(r);await admin();const p=z.object({email:z.string().email().max(254).transform(s=>s.toLowerCase().trim()),name:z.string().trim().min(2).max(160),role:z.enum(['supervisor','admin'])}).strict().safeParse(await r.json());if(!p.success)throw new HttpError(400,'Confira o nome, e-mail e perfil.');const b=p.data;const db=rawDatabase();const old=db.prepare('SELECT * FROM members WHERE email=?').get(b.email) as any;if(old&&!old.disabled)throw new HttpError(409,'Este e-mail já está cadastrado.');db.exec('BEGIN IMMEDIATE');try{if(old){db.prepare('UPDATE members SET name=?,role=?,disabled=0,password_hash=NULL,failed_attempts=0,locked_until=0 WHERE email=? AND primary_admin=0').run(b.name,b.role,b.email);}else{db.prepare('INSERT INTO members(email,user_id,name,role,primary_admin) VALUES (?,?,?,?,0)').run(b.email,randomUUID(),b.name,b.role);}const token=newInvitation(b.email);db.exec('COMMIT');return json({ok:true,inviteUrl:(process.env.APP_ORIGIN||new URL(r.url).origin)+(process.env.PUBLIC_APP_BASE_PATH===undefined?withBase('/ativar'):process.env.PUBLIC_APP_BASE_PATH+'/ativar')+'#'+token},201);}catch(e){db.exec('ROLLBACK');throw e}}catch(e){return errorResponse(e)}}
export async function DELETE(r:Request){try{sameOrigin(r);const m=await admin();const email=new URL(r.url).searchParams.get('email');if(!email||email===m.email)throw new HttpError(400,'Você não pode remover seu próprio acesso.');const db=rawDatabase();const target=db.prepare('SELECT user_id,primary_admin FROM members WHERE email=? AND disabled=0').get(email) as any;if(!target)throw new HttpError(404,'Acesso não encontrado.');if(target.primary_admin)throw new HttpError(403,'O acesso do responsável não pode ser removido.');db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE members SET disabled=1 WHERE email=?').run(email);db.prepare('DELETE FROM sessions WHERE user_id=?').run(target.user_id);db.prepare('DELETE FROM invitations WHERE email=?').run(email);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e}return json({ok:true})}catch(e){return errorResponse(e)}}
