'use client';
import { useEffect,useMemo,useState } from 'react';
import { RefreshCw,Save,Wallet,Building2,Users } from 'lucide-react';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Progress } from '@/components/ui/progress';
import { summarize,budgetStatus,currentReportMonth,type StoreTotals,type SupervisorTotals } from '@/lib/dashboard';
import { money,type Coverage } from '@/lib/coverage';
import { withBase } from '@/lib/paths';
type Props={records:Coverage[],month:string,onMonthChange:(month:string)=>void,onRefresh:()=>void,loading:boolean};
export default function AdminDashboard({records,month,onMonthChange,onRefresh,loading}:Props){
 const selectedMonth=month||currentReportMonth();const report=useMemo(()=>summarize(records,selectedMonth),[records,selectedMonth]);
 const [limit,setLimit]=useState(500000),[input,setInput]=useState('5000'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[settingsReady,setSettingsReady]=useState(false);
 useEffect(()=>{let alive=true;fetch(withBase('/api/dashboard-settings'),{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível consultar o limite.');if(alive){setLimit(d.monthlyLimitCents);setInput(String(d.monthlyLimitCents/100));setSettingsReady(true)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 async function saveLimit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const cents=Math.round(Number(input)*100);if(!Number.isFinite(cents)||cents<100000||cents>500000)throw Error('Informe um valor entre R$ 1.000 e R$ 5.000.');const r=await fetch(withBase('/api/dashboard-settings'),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({monthlyLimitCents:cents})});const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível salvar o limite.');setLimit(d.monthlyLimitCents);setSettingsReady(true);setMessage('Limite atualizado para todos os supervisores.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function leaders(key:'coverageCount'|'supportCount'){const maximum=Math.max(0,...report.supervisors.map(s=>s[key]));return {count:maximum,names:maximum?report.supervisors.filter(s=>s[key]===maximum).map(s=>s.name).join(', '):'Sem chamados no período'}}
 const coverageLeader=leaders('coverageCount'),supportLeader=leaders('supportCount');
 function storeRanking(type:'coverage'|'support'){const count=type==='coverage'?'coverageCount':'supportCount',cost=type==='coverage'?'coverageCents':'supportCents';const rows=report.stores.filter(s=>s[count]>0).sort((a,b)=>b[count]-a[count]||b[cost]-a[cost]||a.name.localeCompare(b.name,'pt-BR'));const max=rows[0]?.[count]||1;return <section className="panel ranking"><div className="section-title"><Building2 size={20}/><h2>Lojas com mais {type==='coverage'?'coberturas':'apoios operacionais'}</h2></div>{!rows.length?<p className="empty-small">Nenhum chamado deste tipo no mês.</p>:<ol>{rows.slice(0,8).map((s,i)=><li key={s.id}><div className="rank-heading"><span><b>{i+1}.</b> {s.name}</span><strong>{s[count]} {s[count]===1?'chamado':'chamados'}</strong></div><Progress value={s[count]/max*100} aria-label={`${s.name}: ${s[count]} chamados`} className={type==='support'?'support-bar':''}/><small>{money(s[cost])}</small></li>)}</ol>}{rows.length>8&&<p className="text-sm mt-3">Exibindo as 8 lojas com mais chamados entre {rows.length} lojas.</p>}</section>}
 return <><div className="dashboard-toolbar"><label>Mês de referência<input aria-label="Mês do dashboard" type="month" required value={selectedMonth} onChange={e=>{if(e.target.value)onMonthChange(e.target.value)}}/></label><button className="secondary" disabled={loading} onClick={onRefresh}><RefreshCw size={16}/>{loading?'Atualizando…':'Atualizar dashboard'}</button></div>{error&&<div className="message error" role="alert">{error}</div>}{message&&<div className="message" role="status">{message}</div>}
 {loading?<div className="panel" role="status">Carregando os valores do mês…</div>:<><div className="dashboard-metrics"><section className="metric-card total-card"><Wallet size={23}/><span>Valor total do mês</span><strong>{money(report.totals.totalCents)}</strong><small>{report.totals.coverageCount+report.totals.supportCount} chamados · cobertura + apoio</small></section><section className="metric-card"><span>Coberturas</span><strong>{money(report.totals.coverageCents)}</strong><small>{report.totals.coverageCount} chamados</small></section><section className="metric-card"><span>Apoios operacionais</span><strong>{money(report.totals.supportCents)}</strong><small>{report.totals.supportCount} chamados</small></section></div>
 <div className="leader-grid"><section className="leader"><span>Supervisor com mais coberturas</span><strong>{coverageLeader.names}</strong><small>{coverageLeader.count} chamados</small></section><section className="leader"><span>Supervisor com mais apoios operacionais</span><strong>{supportLeader.names}</strong><small>{supportLeader.count} chamados</small></section></div>
 <div className="dashboard-grid">{storeRanking('coverage')}{storeRanking('support')}</div>
 <section className="panel supervisor-panel"><div className="section-title"><Users size={20}/><h2>Supervisores: chamados, valores e limite mensal</h2></div><p className="text-sm mb-5">Cobertura e apoio são somados para o limite de cada supervisor. Amarelo a partir de 80%; vermelho ao ultrapassar 100%.</p>{!report.supervisors.length?<p className="empty-small">Ainda não há lançamentos no mês selecionado.</p>:<Table><TableHeader><TableRow><TableHead>Supervisor</TableHead><TableHead>Coberturas</TableHead><TableHead>Apoios</TableHead><TableHead>Valor acumulado</TableHead><TableHead>Limite / utilização</TableHead><TableHead>Lojas atendidas</TableHead></TableRow></TableHeader><TableBody>{report.supervisors.map(s=>{const status=budgetStatus(s.totalCents,settingsReady?limit:0);return <TableRow key={s.id} className={'budget-row '+status.tone}><TableCell><strong>{s.name}</strong><small className="block text-muted-foreground">{s.email}</small></TableCell><TableCell>{s.coverageCount}<small className="block text-muted-foreground">{money(s.coverageCents)}</small></TableCell><TableCell>{s.supportCount}<small className="block text-muted-foreground">{money(s.supportCents)}</small></TableCell><TableCell><strong>{money(s.totalCents)}</strong></TableCell><TableCell className="budget-cell"><span className={'budget-badge '+status.tone}>{settingsReady?status.label:'Consultando limite…'}</span>{settingsReady&&<><div className="budget-numbers"><span>{money(limit)}</span><b>{status.percent.toLocaleString('pt-BR',{maximumFractionDigits:1})}%</b></div><Progress value={Math.min(100,status.percent)} aria-label={`${s.name}: ${status.percent.toFixed(1)}% do limite`} className={'budget-progress '+status.tone}/><small>{s.totalCents>limit?'Excedido: '+money(s.totalCents-limit):'Disponível: '+money(limit-s.totalCents)}</small></>}</TableCell><TableCell><details className="store-details"><summary>Ver {s.stores.length} {s.stores.length===1?'loja':'lojas'}</summary><ul>{s.stores.map(store=><li key={store.id}><b>{store.name}</b><span>{store.coverageCount} coberturas · {store.supportCount} apoios</span><span>{money(store.totalCents)}</span></li>)}</ul></details></TableCell></TableRow>})}</TableBody></Table>}
 </section></>}
 <section className="panel limit-panel"><div><h2>Limite mensal por supervisor</h2><p>Escolha de R$ 1.000 a R$ 5.000. O limite é aplicado a todos os supervisores.</p></div><form onSubmit={saveLimit}><label>Limite (R$)<input type="number" min="1000" max="5000" step="0.01" required value={input} onChange={e=>setInput(e.target.value)} disabled={busy}/></label><button className="primary" disabled={busy||!settingsReady}><Save size={16}/>{busy?'Salvando…':'Salvar limite'}</button></form></section></>;
}
