'use client';
import { useEffect,useState } from 'react';
import { ClipboardList,LockKeyhole } from 'lucide-react';
import { withBase } from '@/lib/paths';
export default function AuthForm({mode}:{mode:'login'|'setup'|'activate'}){
 const [token,setToken]=useState(''),[hasLinkToken,setHasLinkToken]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(mode!=='login'){const value=window.location.hash.slice(1);setToken(value);setHasLinkToken(!!value);if(window.location.hash)history.replaceState(null,'',window.location.pathname);}},[mode]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const data=new FormData(e.currentTarget);const password=String(data.get('password')||'');if(mode!=='login'&&password!==data.get('confirm')){setError('As senhas não coincidem.');return}const body=mode==='login'?{email:data.get('email'),password}:mode==='setup'?{token,name:data.get('name'),email:data.get('email'),password}:{token,password};setBusy(true);try{const r=await fetch(withBase('/api/auth/'+(mode==='activate'?'activate':mode)),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error||'Não foi possível entrar.');window.location.assign(withBase('/'));}catch(e){setError((e as Error).message);setBusy(false)}}
 return <main className="auth-main"><div className="brand mb-7"><span className="mark"><ClipboardList size={24}/></span><span>Controle de Coberturas<small>LOJAS FA · PRESTAÇÃO DE CONTAS</small></span></div><section className="panel auth-panel"><div className="section-title"><LockKeyhole size={22}/><h1>{mode==='login'?'Entrar':mode==='setup'?'Configuração inicial':'Ativar meu acesso'}</h1></div><p className="mb-6">{mode==='login'?'Use o e-mail e a senha do seu acesso.':mode==='setup'?'Cadastre a conta responsável pelo administrativo.':'Defina sua senha para acessar o sistema. O convite é válido por sete dias.'}</p>{error&&<div className="message error" role="alert">{error}</div>}<form onSubmit={submit}><fieldset disabled={busy} className="auth-fields">{mode==='setup'&&<label>Nome completo<input name="name" required minLength={2} maxLength={160} autoComplete="name"/></label>}{mode!=='activate'&&<label>E-mail<input name="email" type="email" required maxLength={254} autoComplete="username"/></label>}{mode!=='login'&&!hasLinkToken&&<label>Código de ativação<input value={token} onChange={e=>setToken(e.target.value)} required autoComplete="off"/></label>}<label>{mode==='login'?'Senha':'Nova senha (pelo menos 12 caracteres)'}<input type="password" name="password" required minLength={mode==='login'?1:12} maxLength={200} autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode!=='login'&&<label>Confirmar senha<input type="password" name="confirm" required minLength={12} maxLength={200} autoComplete="new-password"/></label>}<button className="primary" disabled={busy} type="submit">{busy?'Aguarde…':mode==='login'?'Entrar':mode==='setup'?'Criar conta administrativa':'Definir senha e entrar'}</button></fieldset></form>{mode==='login'?<p className="text-sm mt-6">Para receber ou recuperar seu acesso, solicite um link de ativação ao administrativo.</p>:<a className="inline-block mt-6 text-sm" href={withBase('/login')}>Já tenho senha</a>}</section><p className="text-sm mt-5 text-center">Acesso individual para supervisores e administrativo.</p></main>
}
