import type { Coverage } from './coverage';
import { dateLabel,datesByWeekday,serviceLabel } from './coverage';
import { withBase } from './paths';
export async function buildExcel(records:Coverage[],template:ArrayBuffer){
 const {default:ExcelJS}=await import('exceljs');
 const wb=new ExcelJS.Workbook();await wb.xlsx.load(template);const base=wb.worksheets[0];const model=structuredClone(base.model);wb.removeWorksheet(base.id);
 const groups=new Map<string,Coverage[]>();for(const r of records){const k=r.ownerId+'|'+r.month+'|'+r.serviceType;groups.set(k,[...(groups.get(k)||[]),r]);}
 let idx=0;for(const group of groups.values()){idx++;const first=group[0];const label=((serviceLabel(first.serviceType)+' '+first.ownerName).replace(/[\[\]*?:/\\]/g,' ').slice(0,14)+' '+first.month+' '+idx).slice(0,31);const s=wb.addWorksheet(label);s.model={...structuredClone(model),id:s.id,name:label};if(!s.getCell('A1').isMerged)s.mergeCells('A1:S1');s.getCell('A1').value=`PRESTAÇÃO DE CONTAS - LOJAS FA - ${serviceLabel(first.serviceType).toUpperCase()} - ${first.month.slice(0,4)} - Supervisor ${first.ownerName}`;
 const rowStyle=Array.from({length:19},(_,i)=>structuredClone(s.getRow(3).getCell(i+1).style));
 group.forEach((r,n)=>{const row=n+3;const calendar=datesByWeekday(r.start,r.end);const vals=[r.name,`${dateLabel(r.start)} a ${dateLabel(r.end)}`,r.cpf,r.operation,...Array.from({length:7},(_,d)=>r.weekdays.includes(d)?calendar[d].map(v=>dateLabel(v).slice(0,5)).join('\n'):''),r.month.slice(5)+'/'+r.month.slice(0,4),r.justification,r.details,r.pix,r.thirdParty,r.dailyCents/100,r.days,{formula:`Q${row}*R${row}`,result:r.totalCents/100}];vals.forEach((v,i)=>{const c=s.getRow(row).getCell(i+1);c.style=structuredClone(rowStyle[i]);c.value=v;c.alignment={...c.alignment,vertical:'middle',wrapText:true};});s.getRow(row).height=Math.min(409,Math.max(30,Math.ceil(Math.max(r.justification.length/25,r.details.length/40,r.name.length/35))*15,...r.weekdays.map(d=>calendar[d].length*12+6)));s.getCell(`Q${row}`).numFmt='"R$" #,##0.00';s.getCell(`S${row}`).numFmt='"R$" #,##0.00';s.getCell(`R${row}`).numFmt='0';s.getCell(`C${row}`).numFmt='@';s.getCell(`O${row}`).numFmt='@';});
 s.views=[{state:'frozen',ySplit:2}];s.autoFilter={from:'A2',to:`S${group.length+2}`};s.pageSetup={...s.pageSetup,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,printArea:`A1:S${Math.max(19,group.length+2)}`};
 }
 wb.creator='Controle de Coberturas';wb.created=new Date();wb.calcProperties.fullCalcOnLoad=true;return wb.xlsx.writeBuffer();
}
export async function downloadExcel(records:Coverage[]){if(!records.length)throw new Error('Não há registros para exportar.');const res=await fetch(withBase('/modelo.xlsx'));if(!res.ok)throw new Error('Não foi possível carregar o modelo Excel.');const buffer=await buildExcel(records,await res.arrayBuffer());const blob=new Blob([buffer as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`coberturas-${new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
