import { integer, sqliteTable, text, index } from 'drizzle-orm/sqlite-core';
export const members = sqliteTable('members', {
 email:text('email').primaryKey(), userId:text('user_id').unique(), name:text('name').notNull(), role:text('role').notNull(), primary:integer('primary_admin').notNull().default(0), passwordHash:text('password_hash'), disabled:integer('disabled').notNull().default(0), failedAttempts:integer('failed_attempts').notNull().default(0), lockedUntil:integer('locked_until').notNull().default(0)
});
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>members.userId),expiresAt:integer('expires_at').notNull()},t=>[index('idx_sessions_user').on(t.userId)]);
export const invitations=sqliteTable('invitations',{tokenHash:text('token_hash').primaryKey(),email:text('email').notNull().references(()=>members.email),expiresAt:integer('expires_at').notNull()},t=>[index('idx_invitations_email').on(t.email)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),windowStart:integer('window_start').notNull()});
export const coverages = sqliteTable('coverages', {
 id:text('id').primaryKey(), ownerId:text('owner_id').notNull(), ownerName:text('owner_name').notNull(), ownerEmail:text('owner_email').notNull(), createdAt:text('created_at').notNull(), name:text('name').notNull(), cpf:text('cpf').notNull(), operation:text('operation').notNull(), start:text('start').notNull(), end:text('end').notNull(), month:text('month').notNull(), weekdays:text('weekdays').notNull(), justification:text('justification').notNull(), details:text('details').notNull(), pix:text('pix').notNull(), thirdParty:text('third_party').notNull(), dailyCents:integer('daily_cents').notNull(), days:integer('days').notNull(), totalCents:integer('total_cents').notNull()
},t=>[index('idx_coverages_owner_month').on(t.ownerId,t.month),index('idx_coverages_month').on(t.month)]);
